version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080