CREATE TABLE hitter_projection
(
  id                     INTEGER NOT NULL PRIMARY KEY,
  at_bats                INTEGER,
  batting_average_rating DOUBLE PRECISION,
  caught_stealing        INTEGER,
  doubles                INTEGER,
  games_played           INTEGER,
  hit_by_pitch           INTEGER,
  hits                   INTEGER,
  homerun_rating         DOUBLE PRECISION,
  homeruns               INTEGER,
  league                 VARCHAR(255),
  plate_appearances      INTEGER,
  rbi_rating             DOUBLE PRECISION,
  runs                   INTEGER,
  runs_batted_in         INTEGER,
  runs_rating            DOUBLE PRECISION,
  source                 VARCHAR(255),
  stolen_base_rating     DOUBLE PRECISION,
  stolen_bases           INTEGER,
  strikeouts             INTEGER,
  triples                INTEGER,
  walks                  INTEGER,
  hitter_id              INTEGER REFERENCES player
);